project:
  type: website

website:
  title: "Mapping the Unseen"
  navbar:
    left:
      - text: "Hands-on Exercises"
        menu: 
          - text: "Hands-on Exercise 1.1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-onExercise1.1.qmd"          
          - text: "Hands-on Exercise 1.2"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-onExercise1.2.qmd" 
          - text: "Hands-on Exercise 2.1"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-onExercise2.1.qmd"
          - text: "Hands-on Exercise 2.2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-onExercise2.2.qmd" 
      - text: "In-class Exercises"
        menu: 
          - text: "In-class Exercise 1"
            href: "In-class_Ex/In-class_Ex01/In-classExercise1.qmd" 
          - text: "In-class Exercise 2"
            href: "In-class_Ex/In-class_Ex02/In-classExercise2.qmd" 
          - text: "In-class Exercise 3"
            href: "In-class_Ex/In-class_Ex03/In-classExercise3.qmd"
    right: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    page-layout: full
    smooth-scroll: true
    background-color: "#F5F5F5"
    font-family: "Roboto"
 
editor: visual


